### ISSUE TITLE
Not working when refreshing on nested url.

### ISSUE THREAD

**Issue by mishuagopian** [Wolox/frontend-bootstrap#17]
Not working when refreshing on nested url. CSS broken.

![screen shot 2015-07-07 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/9448790/8551898/ed7b9a1e-24af-11e5-8ee1-76966a0bd49e.png)

**Comment by sbalay** [comment]
fixed by f5439228b645a301e23d27eec4d4cf1bac36bad5
