### ISSUE TITLE
Task to show maintenance page

### ISSUE THREAD

**Issue by epintos** [Wolox/frontend-bootstrap#35]
It would be nice that with a gulp task the page could show a maintenance page like heroku does

**Comment by sbalay** [comment]
Mmm, can you attach a screenshot or explain a little more what heroku does?

**Comment by epintos** [comment]
With heroku you run `heroku maintenance:on` and a static page is shown. You can use a bucket for example and add the url as an environment variable.

You can set also a static page when the server is down too show an error page

You can read more about it [here](https://devcenter.heroku.com/articles/maintenance-mode)

**Comment by sbalay** [comment]
abd487d3a2238dc5759f18724d50a36b08afb83b

**Comment by sbalay** [comment]
b4cc344aa6f7ceb8c60c42c0458eafbdd195e81c
