### ISSUE TITLE
Branches para browserify, angular y react?

### ISSUE THREAD

**Issue by sbalay** [Wolox/frontend-bootstrap#6]

**Comment by guidomb** [comment]
Yo haría forks en vez de branches

**Comment by sbalay** [comment]
No se pueden hacer forks de un repo de una cuenta github en la misma cuenta.

**Comment by guidomb** [comment]
OK bueno entonces branches.

**Comment by sbalay** [comment]
En el futuro vamos a migrar el esquema de branches a un único branch con un generator de [yeoman](http://yeoman.io/authoring/)
