### ISSUE TITLE
Develop kickoff script

### ISSUE THREAD

**Issue by sbalay** [Wolox/frontend-bootstrap#60]
Something like [this](https://github.com/Wolox/rails-bootstrap/blob/master/script/bootstrap) file that is used in rails projects.
This script should replace the module name in angular files, in package.json, bower.json and readme.

**Comment by sbalay** [comment]
Use node

**Comment by mishuagopian** [comment]
https://github.com/Wolox/frontend-bootstrap/pull/64 & https://github.com/Wolox/frontend-bootstrap/pull/65
